#! /usr/bin/env php

<?php

require __DIR__ . '/vendor/autoload.php';

$app = new Symfony\Component\Console\Application('MLB Standings', '0.1.0');

$app->add(new StandingsApp\ShowCommand);

$app->run();
